frase =str(input('Digite nome completo: '))
print('~-'*30)
print(f'Seu nome em Maiúscula é: {frase.upper()}')
print(f'Seu nome em Minúscula é: {frase.lower()}')
palavra = frase.split()
junto = ''.join(palavra)
print(f'Esse nome tem {len(junto)} letras.')
print(f'Primeiro nome é {palavra[0]} e tem {len(palavra[0])} letras')
print('~-'*30)